name: dasinya_tv
description: Dasinya Channel, Movies, Stream
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase (Backend)
  supabase_flutter: ^2.0.0
  
  # Video Players
  video_player: ^2.8.1
  chewie: ^1.7.5
  
  # HTTP & Networking
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7
  
  # Icons
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  # Uncomment if you add custom fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

